name: Update gist with WakaTime stats
on:
  schedule:
    #Runs at 12am IST
    - cron: "30 18 * * *"
jobs:
  update-readme:
    name: Update Readme With Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
